// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcs.demo.domain;

import com.bcs.demo.domain.Patent;

privileged aspect Patent_Roo_JavaBean {
    
    public String Patent.getPatentNumber() {
        return this.patentNumber;
    }
    
    public void Patent.setPatentNumber(String patentNumber) {
        this.patentNumber = patentNumber;
    }
    
}
