// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcs.demo.domain;

import com.bcs.demo.domain.Patent;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Patent_Roo_Configurable {
    
    declare @type: Patent: @Configurable;
    
}
