// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcs.demo.domain;

import com.bcs.demo.domain.Patent;
import com.bcs.demo.domain.PatentDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PatentDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PatentDataOnDemand: @Component;
    
    private Random PatentDataOnDemand.rnd = new SecureRandom();
    
    private List<Patent> PatentDataOnDemand.data;
    
    public Patent PatentDataOnDemand.getNewTransientPatent(int index) {
        Patent obj = new Patent();
        setPatentNumber(obj, index);
        return obj;
    }
    
    public void PatentDataOnDemand.setPatentNumber(Patent obj, int index) {
        String patentNumber = "patentNumber_" + index;
        obj.setPatentNumber(patentNumber);
    }
    
    public Patent PatentDataOnDemand.getSpecificPatent(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Patent obj = data.get(index);
        Long id = obj.getId();
        return Patent.findPatent(id);
    }
    
    public Patent PatentDataOnDemand.getRandomPatent() {
        init();
        Patent obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Patent.findPatent(id);
    }
    
    public boolean PatentDataOnDemand.modifyPatent(Patent obj) {
        return false;
    }
    
    public void PatentDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Patent.findPatentEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Patent' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Patent>();
        for (int i = 0; i < 10; i++) {
            Patent obj = getNewTransientPatent(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
