// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bcs.demo.domain;

import com.bcs.demo.domain.Patent;
import com.bcs.demo.domain.PatentDataOnDemand;
import com.bcs.demo.domain.PatentIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PatentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PatentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PatentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PatentIntegrationTest: @Transactional;
    
    @Autowired
    PatentDataOnDemand PatentIntegrationTest.dod;
    
    @Test
    public void PatentIntegrationTest.testCountPatents() {
        Assert.assertNotNull("Data on demand for 'Patent' failed to initialize correctly", dod.getRandomPatent());
        long count = Patent.countPatents();
        Assert.assertTrue("Counter for 'Patent' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PatentIntegrationTest.testFindPatent() {
        Patent obj = dod.getRandomPatent();
        Assert.assertNotNull("Data on demand for 'Patent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Patent' failed to provide an identifier", id);
        obj = Patent.findPatent(id);
        Assert.assertNotNull("Find method for 'Patent' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Patent' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PatentIntegrationTest.testFindAllPatents() {
        Assert.assertNotNull("Data on demand for 'Patent' failed to initialize correctly", dod.getRandomPatent());
        long count = Patent.countPatents();
        Assert.assertTrue("Too expensive to perform a find all test for 'Patent', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Patent> result = Patent.findAllPatents();
        Assert.assertNotNull("Find all method for 'Patent' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Patent' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PatentIntegrationTest.testFindPatentEntries() {
        Assert.assertNotNull("Data on demand for 'Patent' failed to initialize correctly", dod.getRandomPatent());
        long count = Patent.countPatents();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Patent> result = Patent.findPatentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Patent' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Patent' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PatentIntegrationTest.testFlush() {
        Patent obj = dod.getRandomPatent();
        Assert.assertNotNull("Data on demand for 'Patent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Patent' failed to provide an identifier", id);
        obj = Patent.findPatent(id);
        Assert.assertNotNull("Find method for 'Patent' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPatent(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Patent' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PatentIntegrationTest.testMergeUpdate() {
        Patent obj = dod.getRandomPatent();
        Assert.assertNotNull("Data on demand for 'Patent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Patent' failed to provide an identifier", id);
        obj = Patent.findPatent(id);
        boolean modified =  dod.modifyPatent(obj);
        Integer currentVersion = obj.getVersion();
        Patent merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Patent' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PatentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Patent' failed to initialize correctly", dod.getRandomPatent());
        Patent obj = dod.getNewTransientPatent(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Patent' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Patent' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Patent' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PatentIntegrationTest.testRemove() {
        Patent obj = dod.getRandomPatent();
        Assert.assertNotNull("Data on demand for 'Patent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Patent' failed to provide an identifier", id);
        obj = Patent.findPatent(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Patent' with identifier '" + id + "'", Patent.findPatent(id));
    }
    
}
